### ISSUE TITLE
Can you provide a version with java 11 vs 17?

### ISSUE THREAD

**Issue by agrohe21** [rsvihladremio/dqd#7]

**Comment by rsvihladremio** [comment]
Hey Andy thanks for the issue. The problem we have is we use a lot of version 17 features and the code change would be substantial. Can I suggest instead that you use the docker image here https://github.com/rsvihladremio/dqd/pkgs/container/dqd/244353197?tag=v0.11.4 ?

`docker run --platform=linux/amd64 -d -p 8080:8080 ghcr.io/rsvihladremio/dqd:v0.11.4
`
and you should have a running server on port 8080

**Comment by agrohe21** [comment]
The native binaries are the easiest for me. thanks!

**Comment by agrohe21** [comment]
Is there any way you can do the same for DDC? getting the right java
versions on a machine in an air gapped company can be a PITA.

**Comment by rsvihladremio** [comment]
ddc is compiled down to native code already (it's written in go)
